PrimarySSD:
  model_name: "PrimarySSD"
  hub_mode: True
  model_handle: "https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1"
  label_path: ""
  box_min_score: 0.3
  vehicle_min_score: 0.3
  iou_score: 0.3
  offset_score: 0.3
  max_boxes: 10