efficient:
  model_name: "efficient"
  hub_mode: True
  model_handle: "https://tfhub.dev/tensorflow/efficientdet/lite4/detection/2"
  label_path: "./params/label/mscoco_label_map.yaml" # model label path
  min_score: 0.2
  iou_score: 0.3
  offset_score: 0.3
  max_boxes: 10