FasterRCNN:
  model_name: "FasterRCNN"
  hub_mode: True
  model_handle: "https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1"
  label_path: ""
  box_min_score: 0.1
  vehicle_min_score: 0.3
  iou_score: 0.3
  offset_score: 0.3
  max_boxes: 10