ssd_mobile:
  model_name: "ssd_mobile"
  hub_mode: True
  model_handle: "https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2"
  label_path: "./params/label/mscoco_label_map.yaml" # model label path
  min_score: 0.3
  iou_score: 0.3
  offset_score: 0.3