
# Models
primary_model_name: "Yolov5"       # "primary model args"
recovery_model_name: "ssd_mobile"     # "recovery model args"
box_model_name: ""                    # "box model args"
tracker_model_name: "sort_color"         # "tracker model args"

# DataSet path
run_mode: "Merge" # Single / Parallel / Merge
video_list: [] # video list
video_path: "./video/" # target video path
image_path: "test_images/" # test images path
plan_path: "./params/plan3-15.png"
projection_path: "./params/projection/"
num_of_projection: 3

# Output path
output_base_path: "./output/" # 
run_name: "" # 
detected_path: "detected_images/" #
tracking_path: "tracking_result/" #
trajectory_path: "plan_result/" #

# Developer menu
debug: False
log: True
visible: False
save: True
pipeline: True
citation: True
history: True