Image:
  list:
    0:
    - LOADING DOCK F3 Rampa 11-12
    - LOADING DOCK F3 Rampa 13 - 14
    - LOADING DOCK F3 Rampa 15-16
    - LOADING DOCK F3 Rampa 9-10
  path: temp/
Video:
  list:
    0:
    - LOADING DOCK F3 Rampa 11-12.avi
    - LOADING DOCK F3 Rampa 13 - 14.avi
    - LOADING DOCK F3 Rampa 15-16.avi
    - LOADING DOCK F3 Rampa 9-10.avi
  path: video\targetVideo\
box_model_name: ''
citation: true
debug: false
detected_path: detected_images/
drawing_scale: 0.06579
history: false
image_path: test_images/
log: true
num_of_projection: 3
output_base_path: ./output/
pipeline: true
plan_path: ./params/plan.png
primary_model_name: Yolov5
projection_path: ./params/projection/
provide: Video
recovery_model_name: ssd_mobile
run_mode: Cascade
run_name: ''
save: true
tracker_model_name: sort_color
tracking_path: tracking_result/
trajectory_path: plan_result/
visible: false
